# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b7d8475cf28d21b88631ad40526b13cecef601f4f9333a9a25e0b12e6e71e0ff474d988ca732a7b0807d74b7f3c77ff5f119dacf4a91d8d64e8f3ed98979eb0

test:
  secret_key_base: 1171bc70ca77803d09b133b87f2a8c88c8f4734f7b2ff1e344872f8305aadea5500d38e5c90963d1d48bf155d942ccebfcb3d9f3bc12a828e0dab6fcb368ba6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
